# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import gost_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('gost_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guest',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=gost_app.models.upload_location, width_field=b'width_field'),
        ),
        migrations.AddField(
            model_name='guest',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
