# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gost_app', '0009_auto_20160417_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='friends_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='_guest_friends_list_+', to='gost_app.Guest'),
        ),
    ]
