# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import manager_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalerijaSlikaRestorana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menadzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('ulica', models.CharField(max_length=100)),
                ('grad', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('opis', models.CharField(max_length=1000)),
                ('menadzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.Menadzer')),
                ('slike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.GalerijaSlikaRestorana')),
            ],
        ),
        migrations.CreateModel(
            name='slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=manager_app.models.upload_location, width_field=b'width_field')),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('height_field', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoviRestorana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazivTipa', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='restoran',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.TipoviRestorana'),
        ),
        migrations.AddField(
            model_name='galerijaslikarestorana',
            name='slika',
            field=models.ManyToManyField(blank=True, to='manager_app.slika'),
        ),
    ]
